#!/bin/bash
#My second script on system engineering devops
This script lists all the contents of the current directory
echo "0-current_working_directory.sh 0-current_working_directory.sh~ 1-listit 1-listit~ 1-listit.sh README.md"
